server:
  port: 8082
spring:
  application:
    name: tensquarebase
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.52.130:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
  rabbitmq:
    host: 192.168.52.130
    port: 5672  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
tte: 124578      
      
      
