server: 
  port: 8086
spring: 
  application:  
    name: tensquaregathering #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.52.130:3306/tensquare_gathering?characterEncoding=UTF8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
